// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/cluster.proto

package clusterpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 角色：Master / Backup / Slave
type NodeRole int32

const (
	NodeRole_NODE_ROLE_UNSPECIFIED NodeRole = 0
	NodeRole_NODE_ROLE_MASTER      NodeRole = 1
	NodeRole_NODE_ROLE_BACKUP      NodeRole = 2
	NodeRole_NODE_ROLE_SLAVE       NodeRole = 3
)

// Enum value maps for NodeRole.
var (
	NodeRole_name = map[int32]string{
		0: "NODE_ROLE_UNSPECIFIED",
		1: "NODE_ROLE_MASTER",
		2: "NODE_ROLE_BACKUP",
		3: "NODE_ROLE_SLAVE",
	}
	NodeRole_value = map[string]int32{
		"NODE_ROLE_UNSPECIFIED": 0,
		"NODE_ROLE_MASTER":      1,
		"NODE_ROLE_BACKUP":      2,
		"NODE_ROLE_SLAVE":       3,
	}
)

func (x NodeRole) Enum() *NodeRole {
	p := new(NodeRole)
	*p = x
	return p
}

func (x NodeRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeRole) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_cluster_proto_enumTypes[0].Descriptor()
}

func (NodeRole) Type() protoreflect.EnumType {
	return &file_proto_cluster_proto_enumTypes[0]
}

func (x NodeRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeRole.Descriptor instead.
func (NodeRole) EnumDescriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{0}
}

// 切换类型：0 超时切换，1 故障切换，2 手工指定
type SwitchType int32

const (
	SwitchType_SWITCH_TYPE_TIMEOUT  SwitchType = 0
	SwitchType_SWITCH_TYPE_FAILOVER SwitchType = 1
	SwitchType_SWITCH_TYPE_MANUAL   SwitchType = 2
)

// Enum value maps for SwitchType.
var (
	SwitchType_name = map[int32]string{
		0: "SWITCH_TYPE_TIMEOUT",
		1: "SWITCH_TYPE_FAILOVER",
		2: "SWITCH_TYPE_MANUAL",
	}
	SwitchType_value = map[string]int32{
		"SWITCH_TYPE_TIMEOUT":  0,
		"SWITCH_TYPE_FAILOVER": 1,
		"SWITCH_TYPE_MANUAL":   2,
	}
)

func (x SwitchType) Enum() *SwitchType {
	p := new(SwitchType)
	*p = x
	return p
}

func (x SwitchType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SwitchType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_cluster_proto_enumTypes[1].Descriptor()
}

func (SwitchType) Type() protoreflect.EnumType {
	return &file_proto_cluster_proto_enumTypes[1]
}

func (x SwitchType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SwitchType.Descriptor instead.
func (SwitchType) EnumDescriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{1}
}

type ClusterEventType int32

const (
	ClusterEventType_CLUSTER_EVENT_TYPE_UNSPECIFIED    ClusterEventType = 0
	ClusterEventType_CLUSTER_EVENT_TYPE_FULL_STATE     ClusterEventType = 1
	ClusterEventType_CLUSTER_EVENT_TYPE_DELTA          ClusterEventType = 2
	ClusterEventType_CLUSTER_EVENT_TYPE_LEADER_CHANGED ClusterEventType = 3
)

// Enum value maps for ClusterEventType.
var (
	ClusterEventType_name = map[int32]string{
		0: "CLUSTER_EVENT_TYPE_UNSPECIFIED",
		1: "CLUSTER_EVENT_TYPE_FULL_STATE",
		2: "CLUSTER_EVENT_TYPE_DELTA",
		3: "CLUSTER_EVENT_TYPE_LEADER_CHANGED",
	}
	ClusterEventType_value = map[string]int32{
		"CLUSTER_EVENT_TYPE_UNSPECIFIED":    0,
		"CLUSTER_EVENT_TYPE_FULL_STATE":     1,
		"CLUSTER_EVENT_TYPE_DELTA":          2,
		"CLUSTER_EVENT_TYPE_LEADER_CHANGED": 3,
	}
)

func (x ClusterEventType) Enum() *ClusterEventType {
	p := new(ClusterEventType)
	*p = x
	return p
}

func (x ClusterEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClusterEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_cluster_proto_enumTypes[2].Descriptor()
}

func (ClusterEventType) Type() protoreflect.EnumType {
	return &file_proto_cluster_proto_enumTypes[2]
}

func (x ClusterEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClusterEventType.Descriptor instead.
func (ClusterEventType) EnumDescriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{2}
}

type TunnelNetwork int32

const (
	TunnelNetwork_TUNNEL_NETWORK_UNSPECIFIED TunnelNetwork = 0
	TunnelNetwork_TUNNEL_NETWORK_TCP         TunnelNetwork = 1
	TunnelNetwork_TUNNEL_NETWORK_UNIX        TunnelNetwork = 2
)

// Enum value maps for TunnelNetwork.
var (
	TunnelNetwork_name = map[int32]string{
		0: "TUNNEL_NETWORK_UNSPECIFIED",
		1: "TUNNEL_NETWORK_TCP",
		2: "TUNNEL_NETWORK_UNIX",
	}
	TunnelNetwork_value = map[string]int32{
		"TUNNEL_NETWORK_UNSPECIFIED": 0,
		"TUNNEL_NETWORK_TCP":         1,
		"TUNNEL_NETWORK_UNIX":        2,
	}
)

func (x TunnelNetwork) Enum() *TunnelNetwork {
	p := new(TunnelNetwork)
	*p = x
	return p
}

func (x TunnelNetwork) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TunnelNetwork) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_cluster_proto_enumTypes[3].Descriptor()
}

func (TunnelNetwork) Type() protoreflect.EnumType {
	return &file_proto_cluster_proto_enumTypes[3]
}

func (x TunnelNetwork) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TunnelNetwork.Descriptor instead.
func (TunnelNetwork) EnumDescriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{3}
}

type TunnelDirection int32

const (
	TunnelDirection_TUNNEL_DIRECTION_UNSPECIFIED TunnelDirection = 0
	// FORWARD：本地监听 -> 远程 dial(target)
	TunnelDirection_TUNNEL_DIRECTION_FORWARD TunnelDirection = 1
	// REVERSE：远程监听 -> 本地 dial(target)
	TunnelDirection_TUNNEL_DIRECTION_REVERSE TunnelDirection = 2
)

// Enum value maps for TunnelDirection.
var (
	TunnelDirection_name = map[int32]string{
		0: "TUNNEL_DIRECTION_UNSPECIFIED",
		1: "TUNNEL_DIRECTION_FORWARD",
		2: "TUNNEL_DIRECTION_REVERSE",
	}
	TunnelDirection_value = map[string]int32{
		"TUNNEL_DIRECTION_UNSPECIFIED": 0,
		"TUNNEL_DIRECTION_FORWARD":     1,
		"TUNNEL_DIRECTION_REVERSE":     2,
	}
)

func (x TunnelDirection) Enum() *TunnelDirection {
	p := new(TunnelDirection)
	*p = x
	return p
}

func (x TunnelDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TunnelDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_cluster_proto_enumTypes[4].Descriptor()
}

func (TunnelDirection) Type() protoreflect.EnumType {
	return &file_proto_cluster_proto_enumTypes[4]
}

func (x TunnelDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TunnelDirection.Descriptor instead.
func (TunnelDirection) EnumDescriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{4}
}

type NodeState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClusterId      string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	NodeId         string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Addr           string                 `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"` // gRPC 监听地址（host:port）
	Role           NodeRole               `protobuf:"varint,4,opt,name=role,proto3,enum=cluster.v1.NodeRole" json:"role,omitempty"`
	Term           uint64                 `protobuf:"varint,5,opt,name=term,proto3" json:"term,omitempty"`
	Priority       int32                  `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	SwitchType     SwitchType             `protobuf:"varint,7,opt,name=switch_type,json=switchType,proto3,enum=cluster.v1.SwitchType" json:"switch_type,omitempty"`
	LastSeenUnixMs int64                  `protobuf:"varint,8,opt,name=last_seen_unix_ms,json=lastSeenUnixMs,proto3" json:"last_seen_unix_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NodeState) Reset() {
	*x = NodeState{}
	mi := &file_proto_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeState) ProtoMessage() {}

func (x *NodeState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeState.ProtoReflect.Descriptor instead.
func (*NodeState) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *NodeState) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *NodeState) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeState) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *NodeState) GetRole() NodeRole {
	if x != nil {
		return x.Role
	}
	return NodeRole_NODE_ROLE_UNSPECIFIED
}

func (x *NodeState) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *NodeState) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *NodeState) GetSwitchType() SwitchType {
	if x != nil {
		return x.SwitchType
	}
	return SwitchType_SWITCH_TYPE_TIMEOUT
}

func (x *NodeState) GetLastSeenUnixMs() int64 {
	if x != nil {
		return x.LastSeenUnixMs
	}
	return 0
}

type ElectionHeartbeat struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClusterId       string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	From            *NodeState             `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	TimestampUnixMs int64                  `protobuf:"varint,3,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ElectionHeartbeat) Reset() {
	*x = ElectionHeartbeat{}
	mi := &file_proto_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElectionHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElectionHeartbeat) ProtoMessage() {}

func (x *ElectionHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElectionHeartbeat.ProtoReflect.Descriptor instead.
func (*ElectionHeartbeat) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *ElectionHeartbeat) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ElectionHeartbeat) GetFrom() *NodeState {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *ElectionHeartbeat) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *SubscribeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type ClusterEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClusterId       string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Type            ClusterEventType       `protobuf:"varint,2,opt,name=type,proto3,enum=cluster.v1.ClusterEventType" json:"type,omitempty"`
	States          []*NodeState           `protobuf:"bytes,3,rep,name=states,proto3" json:"states,omitempty"`
	Leader          *NodeState             `protobuf:"bytes,4,opt,name=leader,proto3" json:"leader,omitempty"`
	Term            uint64                 `protobuf:"varint,5,opt,name=term,proto3" json:"term,omitempty"`
	TimestampUnixMs int64                  `protobuf:"varint,6,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClusterEvent) Reset() {
	*x = ClusterEvent{}
	mi := &file_proto_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterEvent) ProtoMessage() {}

func (x *ClusterEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterEvent.ProtoReflect.Descriptor instead.
func (*ClusterEvent) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *ClusterEvent) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ClusterEvent) GetType() ClusterEventType {
	if x != nil {
		return x.Type
	}
	return ClusterEventType_CLUSTER_EVENT_TYPE_UNSPECIFIED
}

func (x *ClusterEvent) GetStates() []*NodeState {
	if x != nil {
		return x.States
	}
	return nil
}

func (x *ClusterEvent) GetLeader() *NodeState {
	if x != nil {
		return x.Leader
	}
	return nil
}

func (x *ClusterEvent) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *ClusterEvent) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

type ManualElectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	TargetNodeId  string                 `protobuf:"bytes,2,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManualElectRequest) Reset() {
	*x = ManualElectRequest{}
	mi := &file_proto_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManualElectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManualElectRequest) ProtoMessage() {}

func (x *ManualElectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManualElectRequest.ProtoReflect.Descriptor instead.
func (*ManualElectRequest) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *ManualElectRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ManualElectRequest) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

type ManualElectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManualElectResponse) Reset() {
	*x = ManualElectResponse{}
	mi := &file_proto_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManualElectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManualElectResponse) ProtoMessage() {}

func (x *ManualElectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManualElectResponse.ProtoReflect.Descriptor instead.
func (*ManualElectResponse) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *ManualElectResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ManualElectResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TunnelEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       TunnelNetwork          `protobuf:"varint,1,opt,name=network,proto3,enum=cluster.v1.TunnelNetwork" json:"network,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // tcp: host:port, unix: /path/to.sock
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelEndpoint) Reset() {
	*x = TunnelEndpoint{}
	mi := &file_proto_cluster_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelEndpoint) ProtoMessage() {}

func (x *TunnelEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelEndpoint.ProtoReflect.Descriptor instead.
func (*TunnelEndpoint) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{6}
}

func (x *TunnelEndpoint) GetNetwork() TunnelNetwork {
	if x != nil {
		return x.Network
	}
	return TunnelNetwork_TUNNEL_NETWORK_UNSPECIFIED
}

func (x *TunnelEndpoint) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type TunnelOpen struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	TunnelId  string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	Direction TunnelDirection        `protobuf:"varint,2,opt,name=direction,proto3,enum=cluster.v1.TunnelDirection" json:"direction,omitempty"`
	// 远端需要 dial 的目标端点（由发起端决定）
	Target        *TunnelEndpoint `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelOpen) Reset() {
	*x = TunnelOpen{}
	mi := &file_proto_cluster_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelOpen) ProtoMessage() {}

func (x *TunnelOpen) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelOpen.ProtoReflect.Descriptor instead.
func (*TunnelOpen) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{7}
}

func (x *TunnelOpen) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *TunnelOpen) GetDirection() TunnelDirection {
	if x != nil {
		return x.Direction
	}
	return TunnelDirection_TUNNEL_DIRECTION_UNSPECIFIED
}

func (x *TunnelOpen) GetTarget() *TunnelEndpoint {
	if x != nil {
		return x.Target
	}
	return nil
}

type TunnelFrame struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TunnelId string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	Seq      uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	// Types that are valid to be assigned to Kind:
	//
	//	*TunnelFrame_Open
	//	*TunnelFrame_Data
	//	*TunnelFrame_Close
	Kind          isTunnelFrame_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelFrame) Reset() {
	*x = TunnelFrame{}
	mi := &file_proto_cluster_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelFrame) ProtoMessage() {}

func (x *TunnelFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelFrame.ProtoReflect.Descriptor instead.
func (*TunnelFrame) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{8}
}

func (x *TunnelFrame) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *TunnelFrame) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *TunnelFrame) GetKind() isTunnelFrame_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *TunnelFrame) GetOpen() *TunnelOpen {
	if x != nil {
		if x, ok := x.Kind.(*TunnelFrame_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *TunnelFrame) GetData() []byte {
	if x != nil {
		if x, ok := x.Kind.(*TunnelFrame_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *TunnelFrame) GetClose() bool {
	if x != nil {
		if x, ok := x.Kind.(*TunnelFrame_Close); ok {
			return x.Close
		}
	}
	return false
}

type isTunnelFrame_Kind interface {
	isTunnelFrame_Kind()
}

type TunnelFrame_Open struct {
	Open *TunnelOpen `protobuf:"bytes,10,opt,name=open,proto3,oneof"`
}

type TunnelFrame_Data struct {
	Data []byte `protobuf:"bytes,11,opt,name=data,proto3,oneof"`
}

type TunnelFrame_Close struct {
	Close bool `protobuf:"varint,12,opt,name=close,proto3,oneof"`
}

func (*TunnelFrame_Open) isTunnelFrame_Kind() {}

func (*TunnelFrame_Data) isTunnelFrame_Kind() {}

func (*TunnelFrame_Close) isTunnelFrame_Kind() {}

// 可选：用于“反向映射”的控制面 RPC（哪个节点在本地开始监听）。
type RemoteListenRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ClusterId string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	MappingId string                 `protobuf:"bytes,2,opt,name=mapping_id,json=mappingId,proto3" json:"mapping_id,omitempty"`
	// 由哪个节点来承接转发（也就是把连接隧道到哪个节点的 TunnelService）。
	TargetNodeId string `protobuf:"bytes,3,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	// 在“当前 RPC 所在节点”上监听的端点。
	Listen *TunnelEndpoint `protobuf:"bytes,4,opt,name=listen,proto3" json:"listen,omitempty"`
	// 在 target_node_id 节点上需要 dial 的目标端点。
	Target        *TunnelEndpoint `protobuf:"bytes,5,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteListenRequest) Reset() {
	*x = RemoteListenRequest{}
	mi := &file_proto_cluster_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteListenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteListenRequest) ProtoMessage() {}

func (x *RemoteListenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteListenRequest.ProtoReflect.Descriptor instead.
func (*RemoteListenRequest) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{9}
}

func (x *RemoteListenRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *RemoteListenRequest) GetMappingId() string {
	if x != nil {
		return x.MappingId
	}
	return ""
}

func (x *RemoteListenRequest) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

func (x *RemoteListenRequest) GetListen() *TunnelEndpoint {
	if x != nil {
		return x.Listen
	}
	return nil
}

func (x *RemoteListenRequest) GetTarget() *TunnelEndpoint {
	if x != nil {
		return x.Target
	}
	return nil
}

type RemoteListenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteListenResponse) Reset() {
	*x = RemoteListenResponse{}
	mi := &file_proto_cluster_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteListenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteListenResponse) ProtoMessage() {}

func (x *RemoteListenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteListenResponse.ProtoReflect.Descriptor instead.
func (*RemoteListenResponse) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{10}
}

func (x *RemoteListenResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RemoteListenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_cluster_proto protoreflect.FileDescriptor

const file_proto_cluster_proto_rawDesc = "" +
	"\n" +
	"\x13proto/cluster.proto\x12\n" +
	"cluster.v1\"\x95\x02\n" +
	"\tNodeState\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04addr\x18\x03 \x01(\tR\x04addr\x12(\n" +
	"\x04role\x18\x04 \x01(\x0e2\x14.cluster.v1.NodeRoleR\x04role\x12\x12\n" +
	"\x04term\x18\x05 \x01(\x04R\x04term\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\x05R\bpriority\x127\n" +
	"\vswitch_type\x18\a \x01(\x0e2\x16.cluster.v1.SwitchTypeR\n" +
	"switchType\x12)\n" +
	"\x11last_seen_unix_ms\x18\b \x01(\x03R\x0elastSeenUnixMs\"\x89\x01\n" +
	"\x11ElectionHeartbeat\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12)\n" +
	"\x04from\x18\x02 \x01(\v2\x15.cluster.v1.NodeStateR\x04from\x12*\n" +
	"\x11timestamp_unix_ms\x18\x03 \x01(\x03R\x0ftimestampUnixMs\"J\n" +
	"\x10SubscribeRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\"\xfd\x01\n" +
	"\fClusterEvent\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x120\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1c.cluster.v1.ClusterEventTypeR\x04type\x12-\n" +
	"\x06states\x18\x03 \x03(\v2\x15.cluster.v1.NodeStateR\x06states\x12-\n" +
	"\x06leader\x18\x04 \x01(\v2\x15.cluster.v1.NodeStateR\x06leader\x12\x12\n" +
	"\x04term\x18\x05 \x01(\x04R\x04term\x12*\n" +
	"\x11timestamp_unix_ms\x18\x06 \x01(\x03R\x0ftimestampUnixMs\"Y\n" +
	"\x12ManualElectRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12$\n" +
	"\x0etarget_node_id\x18\x02 \x01(\tR\ftargetNodeId\"?\n" +
	"\x13ManualElectResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"_\n" +
	"\x0eTunnelEndpoint\x123\n" +
	"\anetwork\x18\x01 \x01(\x0e2\x19.cluster.v1.TunnelNetworkR\anetwork\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"\x98\x01\n" +
	"\n" +
	"TunnelOpen\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\x129\n" +
	"\tdirection\x18\x02 \x01(\x0e2\x1b.cluster.v1.TunnelDirectionR\tdirection\x122\n" +
	"\x06target\x18\x03 \x01(\v2\x1a.cluster.v1.TunnelEndpointR\x06target\"\xa0\x01\n" +
	"\vTunnelFrame\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12,\n" +
	"\x04open\x18\n" +
	" \x01(\v2\x16.cluster.v1.TunnelOpenH\x00R\x04open\x12\x14\n" +
	"\x04data\x18\v \x01(\fH\x00R\x04data\x12\x16\n" +
	"\x05close\x18\f \x01(\bH\x00R\x05closeB\x06\n" +
	"\x04kind\"\xe1\x01\n" +
	"\x13RemoteListenRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x1d\n" +
	"\n" +
	"mapping_id\x18\x02 \x01(\tR\tmappingId\x12$\n" +
	"\x0etarget_node_id\x18\x03 \x01(\tR\ftargetNodeId\x122\n" +
	"\x06listen\x18\x04 \x01(\v2\x1a.cluster.v1.TunnelEndpointR\x06listen\x122\n" +
	"\x06target\x18\x05 \x01(\v2\x1a.cluster.v1.TunnelEndpointR\x06target\"@\n" +
	"\x14RemoteListenResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*f\n" +
	"\bNodeRole\x12\x19\n" +
	"\x15NODE_ROLE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10NODE_ROLE_MASTER\x10\x01\x12\x14\n" +
	"\x10NODE_ROLE_BACKUP\x10\x02\x12\x13\n" +
	"\x0fNODE_ROLE_SLAVE\x10\x03*W\n" +
	"\n" +
	"SwitchType\x12\x17\n" +
	"\x13SWITCH_TYPE_TIMEOUT\x10\x00\x12\x18\n" +
	"\x14SWITCH_TYPE_FAILOVER\x10\x01\x12\x16\n" +
	"\x12SWITCH_TYPE_MANUAL\x10\x02*\x9e\x01\n" +
	"\x10ClusterEventType\x12\"\n" +
	"\x1eCLUSTER_EVENT_TYPE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dCLUSTER_EVENT_TYPE_FULL_STATE\x10\x01\x12\x1c\n" +
	"\x18CLUSTER_EVENT_TYPE_DELTA\x10\x02\x12%\n" +
	"!CLUSTER_EVENT_TYPE_LEADER_CHANGED\x10\x03*`\n" +
	"\rTunnelNetwork\x12\x1e\n" +
	"\x1aTUNNEL_NETWORK_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TUNNEL_NETWORK_TCP\x10\x01\x12\x17\n" +
	"\x13TUNNEL_NETWORK_UNIX\x10\x02*o\n" +
	"\x0fTunnelDirection\x12 \n" +
	"\x1cTUNNEL_DIRECTION_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18TUNNEL_DIRECTION_FORWARD\x10\x01\x12\x1c\n" +
	"\x18TUNNEL_DIRECTION_REVERSE\x10\x022`\n" +
	"\x0fElectionService\x12M\n" +
	"\tHeartbeat\x12\x1d.cluster.v1.ElectionHeartbeat\x1a\x1d.cluster.v1.ElectionHeartbeat(\x010\x012\x8d\x02\n" +
	"\x0eControlService\x12L\n" +
	"\x10SubscribeCluster\x12\x1c.cluster.v1.SubscribeRequest\x1a\x18.cluster.v1.ClusterEvent0\x01\x12U\n" +
	"\x12RequestManualElect\x12\x1e.cluster.v1.ManualElectRequest\x1a\x1f.cluster.v1.ManualElectResponse\x12V\n" +
	"\x11StartRemoteListen\x12\x1f.cluster.v1.RemoteListenRequest\x1a .cluster.v1.RemoteListenResponse2S\n" +
	"\rTunnelService\x12B\n" +
	"\n" +
	"OpenTunnel\x12\x17.cluster.v1.TunnelFrame\x1a\x17.cluster.v1.TunnelFrame(\x010\x01B\x19Z\x17cluster/proto;clusterpbb\x06proto3"

var (
	file_proto_cluster_proto_rawDescOnce sync.Once
	file_proto_cluster_proto_rawDescData []byte
)

func file_proto_cluster_proto_rawDescGZIP() []byte {
	file_proto_cluster_proto_rawDescOnce.Do(func() {
		file_proto_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cluster_proto_rawDesc), len(file_proto_cluster_proto_rawDesc)))
	})
	return file_proto_cluster_proto_rawDescData
}

var file_proto_cluster_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_proto_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_cluster_proto_goTypes = []any{
	(NodeRole)(0),                // 0: cluster.v1.NodeRole
	(SwitchType)(0),              // 1: cluster.v1.SwitchType
	(ClusterEventType)(0),        // 2: cluster.v1.ClusterEventType
	(TunnelNetwork)(0),           // 3: cluster.v1.TunnelNetwork
	(TunnelDirection)(0),         // 4: cluster.v1.TunnelDirection
	(*NodeState)(nil),            // 5: cluster.v1.NodeState
	(*ElectionHeartbeat)(nil),    // 6: cluster.v1.ElectionHeartbeat
	(*SubscribeRequest)(nil),     // 7: cluster.v1.SubscribeRequest
	(*ClusterEvent)(nil),         // 8: cluster.v1.ClusterEvent
	(*ManualElectRequest)(nil),   // 9: cluster.v1.ManualElectRequest
	(*ManualElectResponse)(nil),  // 10: cluster.v1.ManualElectResponse
	(*TunnelEndpoint)(nil),       // 11: cluster.v1.TunnelEndpoint
	(*TunnelOpen)(nil),           // 12: cluster.v1.TunnelOpen
	(*TunnelFrame)(nil),          // 13: cluster.v1.TunnelFrame
	(*RemoteListenRequest)(nil),  // 14: cluster.v1.RemoteListenRequest
	(*RemoteListenResponse)(nil), // 15: cluster.v1.RemoteListenResponse
}
var file_proto_cluster_proto_depIdxs = []int32{
	0,  // 0: cluster.v1.NodeState.role:type_name -> cluster.v1.NodeRole
	1,  // 1: cluster.v1.NodeState.switch_type:type_name -> cluster.v1.SwitchType
	5,  // 2: cluster.v1.ElectionHeartbeat.from:type_name -> cluster.v1.NodeState
	2,  // 3: cluster.v1.ClusterEvent.type:type_name -> cluster.v1.ClusterEventType
	5,  // 4: cluster.v1.ClusterEvent.states:type_name -> cluster.v1.NodeState
	5,  // 5: cluster.v1.ClusterEvent.leader:type_name -> cluster.v1.NodeState
	3,  // 6: cluster.v1.TunnelEndpoint.network:type_name -> cluster.v1.TunnelNetwork
	4,  // 7: cluster.v1.TunnelOpen.direction:type_name -> cluster.v1.TunnelDirection
	11, // 8: cluster.v1.TunnelOpen.target:type_name -> cluster.v1.TunnelEndpoint
	12, // 9: cluster.v1.TunnelFrame.open:type_name -> cluster.v1.TunnelOpen
	11, // 10: cluster.v1.RemoteListenRequest.listen:type_name -> cluster.v1.TunnelEndpoint
	11, // 11: cluster.v1.RemoteListenRequest.target:type_name -> cluster.v1.TunnelEndpoint
	6,  // 12: cluster.v1.ElectionService.Heartbeat:input_type -> cluster.v1.ElectionHeartbeat
	7,  // 13: cluster.v1.ControlService.SubscribeCluster:input_type -> cluster.v1.SubscribeRequest
	9,  // 14: cluster.v1.ControlService.RequestManualElect:input_type -> cluster.v1.ManualElectRequest
	14, // 15: cluster.v1.ControlService.StartRemoteListen:input_type -> cluster.v1.RemoteListenRequest
	13, // 16: cluster.v1.TunnelService.OpenTunnel:input_type -> cluster.v1.TunnelFrame
	6,  // 17: cluster.v1.ElectionService.Heartbeat:output_type -> cluster.v1.ElectionHeartbeat
	8,  // 18: cluster.v1.ControlService.SubscribeCluster:output_type -> cluster.v1.ClusterEvent
	10, // 19: cluster.v1.ControlService.RequestManualElect:output_type -> cluster.v1.ManualElectResponse
	15, // 20: cluster.v1.ControlService.StartRemoteListen:output_type -> cluster.v1.RemoteListenResponse
	13, // 21: cluster.v1.TunnelService.OpenTunnel:output_type -> cluster.v1.TunnelFrame
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_cluster_proto_init() }
func file_proto_cluster_proto_init() {
	if File_proto_cluster_proto != nil {
		return
	}
	file_proto_cluster_proto_msgTypes[8].OneofWrappers = []any{
		(*TunnelFrame_Open)(nil),
		(*TunnelFrame_Data)(nil),
		(*TunnelFrame_Close)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cluster_proto_rawDesc), len(file_proto_cluster_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_cluster_proto_goTypes,
		DependencyIndexes: file_proto_cluster_proto_depIdxs,
		EnumInfos:         file_proto_cluster_proto_enumTypes,
		MessageInfos:      file_proto_cluster_proto_msgTypes,
	}.Build()
	File_proto_cluster_proto = out.File
	file_proto_cluster_proto_goTypes = nil
	file_proto_cluster_proto_depIdxs = nil
}
